### ISSUE TITLE
lost resources after set router base

### ISSUE THREAD

**Issue by lianghx-319** [FEMessage/nuxt-micro-frontend#12]
```js
router: {
    middleware: ['meta', 'auth'],
    mode: 'hash',
    base: 'subapp1',
 },
```

even run sub-App in local, all resources will 404

Nuxt version: 2.11.0
qiankun version: 2.x
platform: macOS
browser: Chrome

**Comment by levy9527** [comment]
可以看demo: https://github.com/FEMessage/nuxt-micro-frontend/tree/dev/examples
