### ISSUE TITLE
Nuxt App Doesn't Render When Used Inside Single-SPA

### ISSUE THREAD

**Issue by munawarb** [FEMessage/nuxt-micro-frontend#17]
Hi,
I'm trying to use your project to turn my Nuxtjs app into a micro frontend. I've configured my app to generate one bundle file called main.js. When I load this main.js into single-spa, I get no DOM. I do have an index root (pages/index.vue). Is there something else I need to include inside single-spa for this app to render?

Part of my single-spa:
```html
    <script type="systemjs-importmap">
        { "imports": { 
            "someRandomName": "http://localhost:3000/_nuxt/main.js",
...
}
</script>
```

Now, I do see the lifecycle hooks firing. My mfe.js is exactly what's provided in the example directory and I do see messages like Nuxt bootstrapped, so I can see the lifecycle hooks are working.

The issue is nothing is rendering in the DOM.

Here is my nuxt.config.js:
```javascript
import colors from 'vuetify/es5/util/colors'
const bodyParser = require("body-parser");
export default {
  render: {
    resourceHints: false
  },
  serverMiddleware: [
    bodyParser.json(), // Register JSON middleware so we can handle application/json requests.
    {path: "/deliver", handler: "~/serverMiddleware/deliver.js"},
    {path: "/save", handler: "~/serverMiddleware/save.js"}
  ],
  mode: "spa",
  /*
  ** Headers of the page
  */
  head: {
    title: 'test', 
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
    ]
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },
  /*
  ** Global CSS
  */
  css: [
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    {src:'~/plugins/v-jsoneditor', mode:'client'}, 
    {src: "~/plugins/localStorage.js", ssr: false}
  ],
  /*
  ** Nuxt.js dev-modules
  */
  buildModules: [
    '@nuxtjs/vuetify',
    'cookie-universal-nuxt'  ,
    ['@femessage/nuxt-micro-frontend', {force: true}]
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    '@nuxtjs/axios',
    'nuxt-graphql-request',
    'cookie-universal-nuxt'  ,
    ['@femessage/nuxt-micro-frontend', {force: true}]
  ],
  graphql: {
    /**
     * Your GraphQL endpoint (required)
     */
    endpoint: 'https://swapi-graphql.netlify.com/.netlify/functions/index',
 
    /**
     * Enable support for AST
     * default: false
     */
    AST: false,
 
    /**
     * Options
     * See: https://github.com/prisma-labs/graphql-request
     */
    options: {},
  },
  
  axios:{
     
  },
  /*
  ** vuetify module configuration
  ** https://github.com/nuxt-community/vuetify-module
  */
  vuetify: {
    customVariables: ['~/assets/variables.scss'],
    theme: {
      disable:true, 
      themes: {
        light: {
          primary: colors.blue,
          accent: colors.blueGrey,
          secondary: colors.amber,
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3
        }
      }
    }
  },
  /*
  ** Build configuration
  */
  build: {
		quiet: false,
		optimization: {splitChunks: {chunks: "async"}, runtimeChunk: false},
		splitChunks: {layouts: false, pages: false, commons: false, vendor: false},
		filenames: {app: () => "main.js"},
    /*
    ** You can extend webpack config here
    */
   serverMiddleware: [
    { path: '/api', handler: '~/server/api.js' },
  ],

    extend (config, ctx) {
    }
  }
}
```

Any help on this would be greatly appreciated!

I would expect the index page to render, but it doesn't.

**Comment by lianghx-319** [comment]
This repo maybe not support single-SPA very well. We consider [qiankun](https://github.com/umijs/qiankun) first. It's core is  single-SPA , so it should be compatible. You can try to expose single-SPA render function in the [client template](https://github.com/FEMessage/nuxt-micro-frontend/blob/dev/lib/client.js)

**Comment by cjfff** [comment]
the systemJs libiary may need [systemjs-webpack-interop](https://github.com/systemjs/systemjs#compatibility-with-webpack) to work in your project. 

our examples has another usage with the nuxt-micro-frontend and you can reference to this [project](https://github.com/FEMessage/nuxt-micro-frontend/tree/dev/examples/single-spa-demo) to change your code

@munawarb

**Comment by munawarb** [comment]
Hi @cjfff, Thanks. We will try this solution and get back to you on whether or not it works.

**Comment by warheartvik** [comment]
@cjfff Hello!

I tried to run this [project](https://github.com/FEMessage/nuxt-micro-frontend/tree/dev/examples/single-spa-demo) and main-project run as spected but nuxt-subapp drops this faltal error Error: Cannot find module 'uniqid'. Maybe i'm missing some dependecies not specified on package.json?

I also tried creating a brand new nuxt project and replicate the nuxt-subapp configuration. And I get the same error when I add this line on nuxt.config.js:
`  
modules: [
       { handler: require(path.resolve(__dirname, '../../../')) }
  ],
`
If i remove that line from nuxt config the nuxt-subapp runs. But, in main-project I got this on console :(
![nuxt-subapp](https://user-images.githubusercontent.com/43218752/95145180-37c6aa00-0740-11eb-8efc-2619f53dcc98.JPG)

Any advise?

**Comment by munawarb** [comment]
@cjfff Same issue here.

**Comment by warheartvik** [comment]
@munawarb Hello!

I found out that the line bellow is looking for main entry file ("main": "lib/module.js") located in package.json 3 levels above single-spa-demo, meaning, at the root folder of the whole [project](https://github.com/FEMessage/nuxt-micro-frontend) 
`
  modules: [
       { handler: require(path.resolve(__dirname, '../../../')) }
  ],
`
So, what I did to run the single-spa-demo in isolatation was to copy lib folder from root, and added it to single-spa-demo folder.
On single-spa-demo/package.json added

`
"main": "lib/module.js",
`
and dependecies required by module.js

`
  "dependencies": {
    "concurrently": "^5.3.0",
    "@nuxt/utils": "latest",
    "lodash.isempty": "^4.4.0",
    "uniqid": "^5.2.0"
  }
`
on nuxt-sub-app/nuxt.config.js . changed
`
  modules: [
       { handler: require(path.resolve(__dirname, '../')) }
  ],
`

cd single-spa-demo
yarn install 
yarn install:all
yarn serve:all

That did it for me

[https://github.com/warheartvik/nuxt-single-spa-demo](https://github.com/warheartvik/nuxt-single-spa-demo)

**Comment by munawarb** [comment]
Hi @warheartvik, Thanks! I'll try this solution.

How did you manage to solve the CORS issue? Chrome keeps blocking the request to localhost:7102/_nuxt/manifest.json on my system. I've tried setting up a proxy using @nuxtjs/proxy but the request is still blocked.

**Comment by munawarb** [comment]
Re: Last, for anyone else struggling with the same-origin policy that makes local testing difficult, you can start chrome like this:
`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --user-data-dir="SOME_OTHER_DATA_DIRECTORY"`

This will disable same-origin policy for that instance of Chrome. For example, mine looks like:
`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --disable-web-security --user-data-dir="c:\users\myUserName\documents\unsec"`

**Comment by munawarb** [comment]
Hi @warheartvik, Your solution worked :) I'm able to render both the sample app and also the Nuxt app I've created. Thanks for figuring this out. You're a star.

**Comment by warheartvik** [comment]
@munawarb I'm glad I could help. 
Just wondering, did you get to render the nuxt apps in universal mode?

**Comment by munawarb** [comment]
Hi @warheartvik, No, I didn't try with SSR. Once I'm done making some refactor changes to my application to make it run without errors in Single-SPA I'll switch it to SSR and let you know what happens.

**Comment by cjfff** [comment]
nuxt.config.js modules config changed to and add the dependencies to your package.json `@femessage/nuxt-micro-frontend`

before

```js
/*
  ** Nuxt.js modules
  */
  modules: [
       { handler: require(path.resolve(__dirname, '../../../')) }
  ],
```

after

```js
  /*
   ** Nuxt.js modules
   */
  modules: ["@femessage/nuxt-micro-frontend"],
```


@munawarb @warheartvik
