### ISSUE TITLE
Cannot read property 'scrollToTop' of undefined when using routing

### ISSUE THREAD

**Issue by munawarb** [FEMessage/nuxt-micro-frontend#26]
## Describe the bug
When I run the example single-spa-demo and I click on a page (either Go To About or Go To Home,) I get this message:
```
Cannot read property 'scrollToTop' of undefined
An error occurred while rendering the page. Check developer tools console for details.
Nuxt.js

MY CONSOLE:
client:52 [WDS] Live Reloading enabled.
Error
client.js?06a0:78 TypeError: Cannot read property 'scrollToTop' of undefined
    at eval (router.scrollBehavior.js?55c4:30)
    at Array.every (<anonymous>)
    at VueRouter.eval (router.scrollBehavior.js?55c4:28)
    at Vue.eval (vue-router.esm.js?8c4f:1733)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)
2
:9000/__webpack_hmr/client:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```
## To Reproduce
1. Start both nuxt-subapp and single-spa-demo.
2. Click on Go To Nuxt. A page with two buttons for About and Home will appear.
3. Click on either of these two buttons.

## Expected behavior
Application should route correctly to either About or Home.

If I go to the address manually by typing localhost:9000/nuxt/home or localhost:9000/nuxt/about, page loads fine.

## environment information
 - OS: Windows 10
 - Browser Chrome

**Comment by cjfff** [comment]
The error throw by vue-router

you can edit the `nuxt-subapp/router/index.js` to fix it

```diff
return new Router({
    ...options,
+   scrollBehavior(to, from, savedPosition) {
+     return { x: 0, y: 0 };
+   },
    routes: fixRoutes(options.routes)
});
```
@munawarb

**Comment by munawarb** [comment]
Thanks @cjfff for the quick response! This fixed the issue.
