### ISSUE TITLE
nuxt子应用，部署nginx，报错

### ISSUE THREAD

**Issue by CIGE-Vince** [FEMessage/nuxt-micro-frontend#30]
ChunkLoadError: Loading chunk 5 failed.
7a87ec1.js:formatted:85514 [import-html-entry]: error occurs while executing normal script
7a87ec1.js:formatted:85541 Uncaught SyntaxError: Unexpected token '<'

子应用用的是仓库中的nuxt-subapp，未做任何改动

主应用是nuxt

有大佬知道是为什么吗

**Comment by cjfff** [comment]
看报错信息是 qiankun 获取你子应用的文件时出错，可能要先排查是否能独立访问的问题，清楚 nginx 配置是否正确 @CIGE-Vince
