### ISSUE TITLE
子应用为nuxt的话，不支持nuxt的router  base属性

### ISSUE THREAD

**Issue by Dbraum** [FEMessage/nuxt-micro-frontend#38]
## Describe the bug
我的子应用是nuxt，我做了nuxt.config.js的router base属性设置，希望借用这个属性切换上下文，但是主应用无法加载子应用。

## Screenshots

![20210407221136](https://user-images.githubusercontent.com/4848041/113880792-62c4b000-97ee-11eb-8dd5-bcb6a196f2a6.jpg)
![20210407221226](https://user-images.githubusercontent.com/4848041/113880817-6821fa80-97ee-11eb-822e-48b8e1808d31.jpg)

## To Reproduce

我照样在提供的examples中，使用nuxt-main-register-demo的主应用，并调整nuxt-subapp配置，
主要的调整是在nuxt-subapp，去掉router文件夹的BASE配置，并在nuxt.config.js文件增加 router.base配置，但是无法生效

## Expected behavior
我希望能支持 nuxt router base 属性配置，如果没时间实现可以同步下调整思路

**Comment by Dbraum** [comment]
已经解决，和nuxt-micro-frontend无关

**Comment by huhaoGitHub** [comment]
请问下如何解决的呢
