### ISSUE TITLE
vue-cli 主项目、nuxt 子项目 项目问题

### ISSUE THREAD

**Issue by Braveheartforyou** [FEMessage/nuxt-micro-frontend#39]
你的 vue-cli-main-demo 项目 我本地运行报错如下：
![image](https://user-images.githubusercontent.com/12381007/119918154-80b2c380-bf9a-11eb-9976-15a7b6aedfc6.png)

另外请教一下  nuxt 本地 资源跨域是因为什么？如图：
![image](https://user-images.githubusercontent.com/12381007/119918269-b192f880-bf9a-11eb-9292-7d1d379aea23.png)

@cjfff

**Comment by Braveheartforyou** [comment]
nuxt.config.js 配置如下：
![image](https://user-images.githubusercontent.com/12381007/119919218-8a3d2b00-bf9c-11eb-9def-f7d368e7c5c2.png)

**Comment by Braveheartforyou** [comment]
modules插件如下：
![image](https://user-images.githubusercontent.com/12381007/119919259-a640cc80-bf9c-11eb-8938-720156a80fd6.png)

**Comment by Braveheartforyou** [comment]
nuxt 版本 2.15.3

**Comment by lianghx-319** [comment]
跨域应该是 dev server 的问题，看看 vue cli 能不能配置dev server 的 cors 吧

**Comment by Braveheartforyou** [comment]
跨域的问题已经解决了，我跑你的 vue-cli-main-demo 项目，nuxt 的 hrm 会报错，你的会报？
![image](https://user-images.githubusercontent.com/12381007/120126507-15adfa80-c1ef-11eb-8bb3-cd619fb32a75.png)
