### ISSUE TITLE
你好，请问这个demo对应的源码可以看吗？

### ISSUE THREAD

**Issue by wendy-banzhuanke** [FEMessage/nuxt-micro-frontend#9]
这个demo:  https://deep-han.github.io/qiankun/react

**Comment by lianghx-319** [comment]
https://github.com/deep-han/qiankun fork 了一份 qiankun 直接改的。页面就在 github pages，只是粗暴的拼在一起。其实有不少生产问题的

**Comment by levy9527** [comment]
新增的demo: https://github.com/FEMessage/nuxt-micro-frontend/tree/dev/examples
